# via [base16](https://github.com/chriskempson/base16)
# colorscheme: [gruvbox-dark-hard by dawikur](https://github.com/dawikur/base16-gruvbox-scheme)
# template: [xfce4-terminal by afg984](https://github.com/afg984/base16-xfce4-terminal)
[Scheme]
Name=Base16-Gruvbox dark, hard
ColorForeground=#d5c4a1
ColorBackground=#1d2021
ColorCursor=#d5c4a1
ColorPalette=#1d2021;#fb4934;#b8bb26;#fabd2f;#83a598;#d3869b;#8ec07c;#d5c4a1;#665c54;#fb4934;#b8bb26;#fabd2f;#83a598;#d3869b;#8ec07c;#fbf1c7
